name: Sync Organization Repo to Forked Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout organization repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main

      - name: add remote-url
        run: |
          git remote add forked-repo https://imnotcoderdude:${{ secrets.VERCEL_GITHUB_TOKEN }}@github.com/imnotcoderdude/Frontend
          git config user.name imnotcoderdude
          git config user.email ${{ secrets.VERCEL_GITHUB_EMAIL }}

      - name: push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean
        run: |
          git remote remove forked-repo